### ISSUE TITLE
CORS error while viewing the site

### ISSUE THREAD

**Issue by abhi1693** [StackStorm-Exchange/index#26]
![image](https://user-images.githubusercontent.com/5083532/147955827-466934da-128d-4427-9fda-31a6d60a8fc5.png)

![image](https://user-images.githubusercontent.com/5083532/147955708-e76c7b61-62b4-4e75-bb02-bcf596b45452.png)

**Comment by cognifloyd** [comment]
We use github pages to host the exchange, so we cannot control the CORS headers.
Github does add the `access-control-allow-origin: *` header.

What version of chrome are you running? What platform?
I do not see the issue on Chrome 96.0.4664.110 (64-bit) on either linux or mac.

**Comment by abhi1693** [comment]
I'm using `Windows Chrome Version 96.0.4664.110 (Official Build) (64-bit)`. I have noticed it mostly happens after the index is updated. The same issue can be viewed on st2 packs page. With that, it fails to parse the `index.json` file.

This issue happens quite regularly

**Comment by cognifloyd** [comment]
Next time you see it, can you look at the headers or see if chrome has anything more specific than "CORS Error"?

Since it's github pages, I don't think there's much we can do. We can adjust the generation of the index, and possibly use `curl` to download a copy of the index and maybe pre-populate some github cache... (totally guessing here). Hopefully more details will point to something we can do about the error, if anything.

**Comment by abhi1693** [comment]
![image](https://user-images.githubusercontent.com/5083532/147963781-78ef697f-5d52-4177-a9b4-5a9279cdd692.png)
![image](https://user-images.githubusercontent.com/5083532/147963782-61bcb7eb-3d4b-40b2-8c7d-3d3040aa8e61.png)
![image](https://user-images.githubusercontent.com/5083532/147963778-5a09ecc1-4c7a-4918-82ac-ea5bb9299b34.png)

It is happening right now again. The header is not present

**Comment by abhi1693** [comment]
And, now the site is getting blocked
![image](https://user-images.githubusercontent.com/5083532/147964272-8dba2f38-d482-42ae-9ec5-a5c820d491ec.png)

**Comment by arm4b** [comment]
Looks like a thing in India :confused: 
* https://stackoverflow.com/questions/70420313/getting-the-website-has-been-blocked-as-per-order-of-ministry-of-electronics-an
* https://www.indiatoday.in/technology/features/story/blocking-websites-is-secret-in-india-now-researchers-are-probing-airtel-and-act-networks-to-reveal-details-1885025-2021-12-07

**Comment by abhi1693** [comment]
That's wierd because it's back online. I'm only seeing all these issues right after an index update by the ci

**Comment by arm4b** [comment]
I guess some small percentage of IP ranges might be blocked randomly belonging to CloudFlare (acts as a proxy for StackStorm Exchange) in India which might the reason why you're getting some of the responses wrong (missing `access-control-allow-origin: *` in the response headers for Exchange index json).
The fact of propagating to CloudFlare CDN the fresh regenerated Exchange index version might be the reason why it fails first and works later when different CDN edge servers are used.
¯\_(ツ)_/¯

**Comment by arm4b** [comment]
Resolved in https://github.com/StackStorm-Exchange/exchange-incubator/issues/173
Please re-open if the issue appears again.
